-- MySQL Script generated by MySQL Workbench
-- Tue Nov 13 11:59:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Homebeer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Homebeer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Homebeer` DEFAULT CHARACTER SET utf8 ;
USE `Homebeer` ;

-- -----------------------------------------------------
-- Table `Homebeer`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Homebeer`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(63) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `cpfcnpj` VARCHAR(18) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `numCartao` VARCHAR(20) NULL,
  `valCartao` VARCHAR(5) NULL,
  `codsCartao` VARCHAR(3) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `cpfcnpj_UNIQUE` (`cpfcnpj` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Homebeer`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Homebeer`.`Produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `alcoolica` VARCHAR(1) NOT NULL,
  `quantidade` DECIMAL NOT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Homebeer`.`Usuarios_vendem_Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Homebeer`.`Usuarios_vendem_Produtos` (
  `Usuario_idUsuario` INT NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Produtos_idProdutos`),
  INDEX `fk_Usuario_has_Produtos_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Produtos_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Produtos_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Homebeer`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `Homebeer`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'georgetonjr' IDENTIFIED BY 'root';

GRANT ALL ON `Homebeer`.* TO 'georgetonjr';
GRANT SELECT ON TABLE `Homebeer`.* TO 'georgetonjr';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `Homebeer`.* TO 'georgetonjr';
GRANT SELECT, INSERT, TRIGGER ON TABLE `Homebeer`.* TO 'georgetonjr';
GRANT EXECUTE ON ROUTINE `Homebeer`.* TO 'georgetonjr';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
