-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 19:59:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema homebeer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homebeer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homebeer` DEFAULT CHARACTER SET utf8 ;
USE `homebeer` ;

-- -----------------------------------------------------
-- Table `homebeer`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cpfcnpj` VARCHAR(18) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `userCreated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `cpfcnpj_UNIQUE` (`cpfcnpj` ASC) ,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homebeer`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS produto (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `marca_produto` VARCHAR(45) NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `quantidade` DECIMAL NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homebeer`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Carrinho (
  `idcarrinho` INT NOT NULL AUTO_INCREMENT,
  `quantidade_produtos` DECIMAL NULL,
  `preco_total` FLOAT NULL,
  `usuario_userid` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  INDEX `fk_Carrinho_usuario_idx` (`usuario_userid` ASC),
  INDEX `fk_Carrinho_produto1_idx` (`produto_idproduto` ASC),
  CONSTRAINT `fk_Carrinho_usuario`
    FOREIGN KEY (`usuario_userid`)
    REFERENCES `homebeer`.`usuario` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrinho_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `homebeer`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `homebeer` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `homebeer`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
